<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/input_map_req_1.map" md5sum="3a01c3825f59f7cabe3c7d839ebc97ff" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		input_map_req_1.map
*   Map declaration(s):	input_map_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FBolivariano%252FTransporteService%257Doperation1RequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FBolivariano%252FFlatFileImport1%257DretrieveFlatFileRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="wsdl.http://Bolivariano/TransporteService"
    xmlns:in2="http://Bolivariano/TransporteService"
    xmlns:io3="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="http://Bolivariano"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out5="http://www.ibm.com/xmlns/prod/websphere/j2ca/flatfile/flatfile"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/j2ca/flatfile/transporteretrievewrapper"
    xmlns:out7="http://Bolivariano/FlatFileImport1"
    xmlns:out8="http://www.ibm.com/xmlns/prod/websphere/j2ca/flatfile/transporteretrievewrapperbg"
    xmlns:io="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out2="http://com/ibm/j2ca/fault"
    xmlns:out9="wsdl.http://Bolivariano/FlatFileImport1"
    xmlns:io2="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/base/unstructuredcontent"
    xmlns:out10="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out4="http://com/ibm/j2ca/fault/afcfault"
    xmlns:map="http://Bolivariano/xslt/input_map_req_1"
    exclude-result-prefixes="xalan str set in math map exsl in2 date"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:input_map_req_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map_req_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out9:retrieveFlatFileRequestMsg'"/>
      </xsl:attribute>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map_req_12">
    <xsl:param name="body"/>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
