<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/output_map_res_1.map" md5sum="7c92f300567b0532b9764090ac10b52d" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		output_map_res_1.map
*   Map declaration(s):	output_map_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FBolivariano%252FFlatFileImport1%257DretrieveFlatFileResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FBolivariano%252FTransporteService%257Doperation1ResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://Bolivariano"
    xmlns:in5="http://www.ibm.com/xmlns/prod/websphere/j2ca/flatfile/flatfile"
    xmlns:in6="http://www.ibm.com/xmlns/prod/websphere/j2ca/flatfile/transporteretrievewrapper"
    xmlns:in7="http://Bolivariano/FlatFileImport1"
    xmlns:in8="http://www.ibm.com/xmlns/prod/websphere/j2ca/flatfile/transporteretrievewrapperbg"
    xmlns:in2="http://com/ibm/j2ca/fault"
    xmlns:in9="wsdl.http://Bolivariano/FlatFileImport1"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/base/unstructuredcontent"
    xmlns:in10="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:in4="http://com/ibm/j2ca/fault/afcfault"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out="wsdl.http://Bolivariano/TransporteService"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out2="http://Bolivariano/TransporteService"
    xmlns:map="http://Bolivariano/xslt/output_map_res_1"
    exclude-result-prefixes="set in10 in math exsl in2 date in3 in4 xalan in5 in6 str in7 in8 in9 map"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:output_map_res_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:operation1ResponseMsg'"/>
      </xsl:attribute>
      <out2:operation1Response>
        <output1 xsi:nil="true"/>
      </out2:operation1Response>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_12">
    <xsl:param name="body"/>
    <out2:operation1Response>
      <output1 xsi:nil="true"/>
    </out2:operation1Response>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
