<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="com/touresbalon/transforms/dataMappingUpdateReq.map" md5sum="24b42dd6e3d2f43b4c608ec66ff7ba6a" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		dataMappingUpdateReq.map
*   Map declaration(s):	dataMappingUpdateReq
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FOrderModule%252Fcom%252Ftouresbalon%252Finterfaces%252FOrderServiceIF%257DupdateOrderRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fservice.model.orders.oms.touresbalon.com%252F%257DupdateStateOrder/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://CommonDomain/com/touresbalon/bo"
    xmlns:in2="wsdl.http://OrderModule/com/touresbalon/interfaces/OrderServiceIF"
    xmlns:in3="http://orders.oms.touresbalon.com/"
    xmlns:in4="http://OrderModule/com/touresbalon/interfaces/OrderServiceIF"
    xmlns:out="wsdl.http://service.model.orders.oms.touresbalon.com/"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://service.model.orders.oms.touresbalon.com/"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://OMSModule/com/touresbalon/transforms/dataMappingUpdateReq"
    exclude-result-prefixes="xalan str set in math map exsl in2 date in3 in4"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:dataMappingUpdateReq"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:dataMappingUpdateReq">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:updateStateOrder'"/>
      </xsl:attribute>
      <!-- a simple data mapping: "in4:updateOrder/request/ordId"(string) to "out2:idOrder"(string) -->
      <out2:idOrder>
        <xsl:value-of select="in4:updateOrder/request/ordId"/>
      </out2:idOrder>
      <!-- a simple data mapping: "in4:updateOrder/request/status"(string) to "out2:state"(string) -->
      <out2:state>
        <xsl:value-of select="in4:updateOrder/request/status"/>
      </out2:state>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:dataMappingUpdateReq2">
    <xsl:param name="body"/>
    <!-- a simple data mapping: "$body/in4:updateOrder/request/ordId"(string) to "out2:idOrder"(string) -->
    <out2:idOrder>
      <xsl:value-of select="$body/in4:updateOrder/request/ordId"/>
    </out2:idOrder>
    <!-- a simple data mapping: "$body/in4:updateOrder/request/status"(string) to "out2:state"(string) -->
    <out2:state>
      <xsl:value-of select="$body/in4:updateOrder/request/status"/>
    </out2:state>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
