<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/MapHttpResponse_res_1.map" md5sum="7db6843ea92e7ad74e11f749e0690299" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		MapHttpResponse_res_1.map
*   Map declaration(s):	MapHttpResponse_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FLB_Customer%252FCustomerService%257DaddCostumerResponseMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FLB_Customer%252FCustomerService%257DaddCostumerResponseMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="wsdl.http://LB_Customer/CustomerService"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io7="http://MM_CustomerService"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io9="http://LB_Customer/CustomerService"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://MM_CustomerService/xslt/MapHttpResponse_res_1"
    exclude-result-prefixes="xalan str set math map exsl date"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="io2:smo" mode="map:MapHttpResponse_res_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:MapHttpResponse_res_1">
    <io2:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io5:addCostumerResponseMsg'"/>
        </xsl:attribute>
        <io9:addCostumerResponse>
          <response>
            <!-- a simple data mapping: "headers/HTTPHeader/control/io6:StatusCode"(int) to "statusCode"(string) -->
            <xsl:if test="headers/HTTPHeader/control/io6:StatusCode">
              <statusCode>
                <xsl:value-of select="headers/HTTPHeader/control/io6:StatusCode"/>
              </statusCode>
            </xsl:if>
            <!-- a simple data mapping: "headers/HTTPHeader/control/io6:ReasonPhrase"(string) to "reasonPhrase"(string) -->
            <xsl:if test="headers/HTTPHeader/control/io6:ReasonPhrase">
              <reasonPhrase>
                <xsl:value-of select="headers/HTTPHeader/control/io6:ReasonPhrase"/>
              </reasonPhrase>
            </xsl:if>
          </response>
        </io9:addCostumerResponse>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:MapHttpResponse_res_12">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io5:addCostumerResponseMsg'"/>
      </xsl:attribute>
      <io9:addCostumerResponse>
        <response>
          <!-- a simple data mapping: "$smo/headers/HTTPHeader/control/io6:StatusCode"(int) to "statusCode"(string) -->
          <xsl:if test="$smo/headers/HTTPHeader/control/io6:StatusCode">
            <statusCode>
              <xsl:value-of select="$smo/headers/HTTPHeader/control/io6:StatusCode"/>
            </statusCode>
          </xsl:if>
          <!-- a simple data mapping: "$smo/headers/HTTPHeader/control/io6:ReasonPhrase"(string) to "reasonPhrase"(string) -->
          <xsl:if test="$smo/headers/HTTPHeader/control/io6:ReasonPhrase">
            <reasonPhrase>
              <xsl:value-of select="$smo/headers/HTTPHeader/control/io6:ReasonPhrase"/>
            </reasonPhrase>
          </xsl:if>
        </response>
      </io9:addCostumerResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
