<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="com/touresbalon/transforms/xslDataMappingError.map" md5sum="3bc8bbd4aef87a0842bdc9b7321b60b0" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		xslDataMappingError.map
*   Map declaration(s):	xslDataMappingError
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FAccommodationModule%252FJDBCImport%257DretrieveallDannCarltonAvailabilityBGRecordNotFoundFaultMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FAccommodationLib%252Fcom%252Ftouresbalon%252Finterfaces%252FAccommodationServiceIF%257DcheckAvailability_businessErrorMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://AccommodationModule/JDBCImport"
    xmlns:in2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/danncarltonavailability"
    xmlns:in3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/danncarltonavailabilitybg"
    xmlns:in4="http://com/ibm/j2ca/fault"
    xmlns:in5="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/danncarltonavailabilitycontainer"
    xmlns:in6="wsdl.http://AccommodationModule/JDBCImport"
    xmlns:in7="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:in8="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out="http://CommonDomain/com/touresbalon/bo"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="http://AccommodationLib/com/touresbalon/interfaces/AccommodationServiceIF"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="wsdl.http://AccommodationLib/com/touresbalon/interfaces/AccommodationServiceIF"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out4="http://AccommodationLib/com/touresbalon/bo"
    xmlns:map="http://AccommodationModule/com/touresbalon/transforms/xslDataMappingError"
    exclude-result-prefixes="set in math exsl in2 in3 date in4 xalan in5 in6 str in7 in8 map"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:xslDataMappingError"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:xslDataMappingError">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:checkAvailability_businessErrorMsg'"/>
      </xsl:attribute>
      <out2:checkAvailabilityFault1_businessError>
        <!-- a simple data mapping: "in:RecordNotFoundFault_element/errorCode"(string) to "faultCode"(string) -->
        <xsl:if test="in:RecordNotFoundFault_element/errorCode">
          <faultCode>
            <xsl:value-of select="in:RecordNotFoundFault_element/errorCode"/>
          </faultCode>
        </xsl:if>
        <!-- a simple data mapping: "in:RecordNotFoundFault_element/message"(string) to "faultString"(string) -->
        <xsl:if test="in:RecordNotFoundFault_element/message">
          <faultString>
            <xsl:value-of select="in:RecordNotFoundFault_element/message"/>
          </faultString>
        </xsl:if>
      </out2:checkAvailabilityFault1_businessError>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:xslDataMappingError2">
    <xsl:param name="body"/>
    <out2:checkAvailabilityFault1_businessError>
      <!-- a simple data mapping: "$body/in:RecordNotFoundFault_element/errorCode"(string) to "faultCode"(string) -->
      <xsl:if test="$body/in:RecordNotFoundFault_element/errorCode">
        <faultCode>
          <xsl:value-of select="$body/in:RecordNotFoundFault_element/errorCode"/>
        </faultCode>
      </xsl:if>
      <!-- a simple data mapping: "$body/in:RecordNotFoundFault_element/message"(string) to "faultString"(string) -->
      <xsl:if test="$body/in:RecordNotFoundFault_element/message">
        <faultString>
          <xsl:value-of select="$body/in:RecordNotFoundFault_element/message"/>
        </faultString>
      </xsl:if>
    </out2:checkAvailabilityFault1_businessError>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
