<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="com/touresbalon/transforms/aa/input_map.map" md5sum="e74eef24fabd5a7c21623f1d73f37221" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		input_map.map
*   Map declaration(s):	input_map
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTransportationLib%257DcheckAvailabilityRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Ftempuri.org%252F%257DcheckAvailabilitySoapIn/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="wsdl.http://TransportationLib"
    xmlns:in2="http://CommonDomain/com/touresbalon/bo"
    xmlns:in3="http://TransportLib/com/touresbalon/bo"
    xmlns:in4="http://TransportationLib"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:out="http://tempuri.org/"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out2="wsdl.http://tempuri.org/"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:MapUtils="xalan://com.ibm.wbiserver.transform.util.MapUtils"
    xmlns:map="http://AmericanAirlinesModule/com/touresbalon/transforms/xslTransforms"
    exclude-result-prefixes="xalan str set MapUtils in math map exsl in2 date in3 in4"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:input_map"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:checkAvailabilitySoapIn'"/>
      </xsl:attribute>
      <out:checkAvailability>
        <out:consultarVuelo>
          <!-- a simple data mapping: "in4:checkAvailability/in4:request/ciudadOrigen"(string) to "out:CodigoCiudadOrigen"(string) -->
          <xsl:if test="in4:checkAvailability/in4:request/ciudadOrigen">
            <out:CodigoCiudadOrigen>
              <xsl:value-of select="in4:checkAvailability/in4:request/ciudadOrigen"/>
            </out:CodigoCiudadOrigen>
          </xsl:if>
          <!-- a simple data mapping: "in4:checkAvailability/in4:request/ciudadDestino"(string) to "out:CodigoCiudadDestino"(string) -->
          <xsl:if test="in4:checkAvailability/in4:request/ciudadDestino">
            <out:CodigoCiudadDestino>
              <xsl:value-of select="in4:checkAvailability/in4:request/ciudadDestino"/>
            </out:CodigoCiudadDestino>
          </xsl:if>
          <!-- a simple data mapping: "in4:checkAvailability/in4:request/travelDate"(date) to "out:FechaVuelo"(dateTime) -->
          <out:FechaVuelo>
            <!-- variables for custom code -->
            <xsl:variable name="travelDate" select="in4:checkAvailability/in4:request/travelDate"/>
            <xsl:value-of select="MapUtils:dateToDateTime($travelDate, '1970-01-01T00:00:00')"/>
          </out:FechaVuelo>
        </out:consultarVuelo>
      </out:checkAvailability>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map2">
    <xsl:param name="body"/>
    <out:checkAvailability>
      <out:consultarVuelo>
        <!-- a simple data mapping: "$body/in4:checkAvailability/in4:request/ciudadOrigen"(string) to "out:CodigoCiudadOrigen"(string) -->
        <xsl:if test="$body/in4:checkAvailability/in4:request/ciudadOrigen">
          <out:CodigoCiudadOrigen>
            <xsl:value-of select="$body/in4:checkAvailability/in4:request/ciudadOrigen"/>
          </out:CodigoCiudadOrigen>
        </xsl:if>
        <!-- a simple data mapping: "$body/in4:checkAvailability/in4:request/ciudadDestino"(string) to "out:CodigoCiudadDestino"(string) -->
        <xsl:if test="$body/in4:checkAvailability/in4:request/ciudadDestino">
          <out:CodigoCiudadDestino>
            <xsl:value-of select="$body/in4:checkAvailability/in4:request/ciudadDestino"/>
          </out:CodigoCiudadDestino>
        </xsl:if>
        <!-- a simple data mapping: "$body/in4:checkAvailability/in4:request/travelDate"(date) to "out:FechaVuelo"(dateTime) -->
        <out:FechaVuelo>
          <!-- variables for custom code -->
          <xsl:variable name="travelDate" select="$body/in4:checkAvailability/in4:request/travelDate"/>
          <xsl:value-of select="MapUtils:dateToDateTime($travelDate, '1970-01-01T00:00:00')"/>
        </out:FechaVuelo>
      </out:consultarVuelo>
    </out:checkAvailability>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
