<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="AccommodationCallbackIF" targetNamespace="http://OrderManagementLib/com/touresbalon/interfaces/AccommodationCallbackIF" xmlns:bons1="http://OrderManagementLib/com/touresbalon/bo" xmlns:tns="http://OrderManagementLib/com/touresbalon/interfaces/AccommodationCallbackIF" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://OrderManagementLib/com/touresbalon/interfaces/AccommodationCallbackIF">
      <xsd:import namespace="http://OrderManagementLib/com/touresbalon/bo" schemaLocation="../bo/LodgingResponse.xsd"/>
      <xsd:element name="confirm">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="response" nillable="true" type="bons1:LodgingResponse"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="confirmRequestMsg">
    <wsdl:part element="tns:confirm" name="confirmParameters"/>
  </wsdl:message>
    <wsdl:portType name="AccommodationCallbackIF">
    <wsdl:operation name="confirm">
      <wsdl:input message="tns:confirmRequestMsg" name="confirmRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>