<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="TransportCallbackIF_TransportCallbackIFHttp_Service" targetNamespace="http://OrderManagementLib/com/touresbalon/interfaces/TransportCallbackIF" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://OrderManagementLib/com/touresbalon/interfaces/TransportCallbackIF" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="TransportCallbackIF.wsdl" namespace="http://OrderManagementLib/com/touresbalon/interfaces/TransportCallbackIF"/>
  <wsdl:binding name="TransportCallbackIF_TransportCallbackIFHttpBinding" type="this:TransportCallbackIF">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="confirm">
      <soap12:operation soapAction="http://OrderManagementLib/com/touresbalon/interfaces/TransportCallbackIF/TransportCallbackIF/confirm"/>
      <wsdl:input name="confirmRequest">
        <soap12:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TransportCallbackIF_TransportCallbackIFHttpService">
    <wsdl:port binding="this:TransportCallbackIF_TransportCallbackIFHttpBinding" name="TransportCallbackIF_TransportCallbackIFHttpPort">
      <soap12:address location="http://localhost:9080/OrderManagementWeb/sca/TransportCallbackIF"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>