<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="com/touresbalon/transforms/aa/xslMappingReservationData.map" md5sum="bde0029cfb0f0b97e5a882597a5eb5b2" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		xslMappingReservationData.map
*   Map declaration(s):	xslMappingReservationData
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FTransportationLib%257DmakeReservationRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Ftempuri.org%252F%257DbookingFlightSoapIn/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="wsdl.http://TransportationLib"
    xmlns:in2="http://CommonDomain/com/touresbalon/bo"
    xmlns:in3="http://TransportLib/com/touresbalon/bo"
    xmlns:in4="http://TransportationLib"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:out="http://tempuri.org/"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out2="wsdl.http://tempuri.org/"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://AmericanAirlinesModule/com/touresbalon/transforms/xslMappingData"
    exclude-result-prefixes="xalan str set in math map exsl in2 date in3 in4"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:xslMappingReservationData"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:xslMappingReservationData">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:bookingFlightSoapIn'"/>
      </xsl:attribute>
      <out:bookingFlight>
        <out:informacionReserva>
          <!-- a for-each transform: "content"(Reservation) to "out:InformacionReserva"(InformacionReserva) -->
          <xsl:apply-templates select="in4:makeReservation/in4:request/content" mode="localContentToInformacionReserva_1016252454"/>
        </out:informacionReserva>
      </out:bookingFlight>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:xslMappingReservationData2">
    <xsl:param name="body"/>
    <out:bookingFlight>
      <out:informacionReserva>
        <!-- a for-each transform: "content"(Reservation) to "out:InformacionReserva"(InformacionReserva) -->
        <xsl:apply-templates select="$body/in4:makeReservation/in4:request/content" mode="localContentToInformacionReserva_1016252454"/>
      </out:informacionReserva>
    </out:bookingFlight>
  </xsl:template>

  <!-- This rule represents a for-each transform: "content" to "out:InformacionReserva".  -->
  <xsl:template match="content"  mode="localContentToInformacionReserva_1016252454">
    <out:InformacionReserva>
      <!-- a simple data mapping: "identificacion"(string) to "out:Identificacion"(string) -->
      <xsl:if test="identificacion">
        <out:Identificacion>
          <xsl:value-of select="identificacion"/>
        </out:Identificacion>
      </xsl:if>
      <!-- a simple data mapping: "nombre"(string) to "out:Nombre"(string) -->
      <xsl:if test="nombre">
        <out:Nombre>
          <xsl:value-of select="nombre"/>
        </out:Nombre>
      </xsl:if>
      <!-- a simple data mapping: "apellido"(string) to "out:Apellido"(string) -->
      <xsl:if test="apellido">
        <out:Apellido>
          <xsl:value-of select="apellido"/>
        </out:Apellido>
      </xsl:if>
      <!-- a simple data mapping: "numeroViaje"(string) to "out:NumeroVuelo"(string) -->
      <xsl:if test="numeroViaje">
        <out:NumeroVuelo>
          <xsl:value-of select="numeroViaje"/>
        </out:NumeroVuelo>
      </xsl:if>
      <!-- a simple data mapping: "codigoCiudadOrigen"(string) to "out:CodigoCiudadOrigen"(string) -->
      <xsl:if test="codigoCiudadOrigen">
        <out:CodigoCiudadOrigen>
          <xsl:value-of select="codigoCiudadOrigen"/>
        </out:CodigoCiudadOrigen>
      </xsl:if>
      <!-- a simple data mapping: "codigoCiudadDestino"(string) to "out:CodigoCiudadDestino"(string) -->
      <xsl:if test="codigoCiudadDestino">
        <out:CodigoCiudadDestino>
          <xsl:value-of select="codigoCiudadDestino"/>
        </out:CodigoCiudadDestino>
      </xsl:if>
      <!-- a simple data mapping: "numeroSilla"(string) to "out:NumeroSilla"(string) -->
      <xsl:if test="numeroSilla">
        <out:NumeroSilla>
          <xsl:value-of select="numeroSilla"/>
        </out:NumeroSilla>
      </xsl:if>
      <!-- a simple data mapping: "fechaSalida"(dateTime) to "out:FechaSalida"(dateTime) -->
      <out:FechaSalida>
        <xsl:value-of select="fechaSalida"/>
      </out:FechaSalida>
      <!-- a simple data mapping: "orderID"(string) to "out:OrderID"(string) -->
      <xsl:if test="orderID">
        <out:OrderID>
          <xsl:value-of select="orderID"/>
        </out:OrderID>
      </xsl:if>
    </out:InformacionReserva>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
