CONNECT  'jdbc:derby:DevWorks;create=true';


drop TABLE DevWorks.JobReq;

create TABLE DevWorks.JobReq (
 reqID integer  NOT NULL primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
 datePosted timestamp,
 jobTitle varchar(100),
 jobType varchar(100),
 jobLevel varchar(100),
 country varchar(100),
 city varchar(100),
 state varchar(100),
 zipcode varchar(100),
 hiringMgr varchar(100),
 hiringEmail varchar(100),
 division varchar(100),
 applyByDate date,
 jobDesc varchar(1024)
);

drop TABLE DevWorks.UserList;
create TABLE DevWorks.UserList (
 userid varchar(100) PRIMARY KEY NOT NULL ,
 fullname varchar(100),
 email varchar(100)
);
insert INTO DevWorks.UserList (userid, fullname, email) VALUES ('admin','Bill 
Griffith','wgriffith@us.ibm.com');
insert INTO DevWorks.UserList (userid, fullname, email) VALUES ('joe','Joe 
Blow','joe@acme.com');

drop TABLE DevWorks.PickListItem;
create TABLE DevWorks.PickListItem (
 id integer NOT NULL primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) ,
 name varchar(100),
 type varchar(100)
);
insert INTO DevWorks.PickListItem(name, type)VALUES ('IT Specialist', 'JobType');
insert INTO DevWorks.PickListItem(name, type)VALUES ('IT Architect', 'JobType');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Manager', 'JobType');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Executive', 'JobType');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Software', 'Division');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Hardware', 'Division');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Sales', 'Division');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Services', 'Division');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Band 6', 'JobLevel');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Band 7', 'JobLevel');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Band 8', 'JobLevel');
insert INTO DevWorks.PickListItem(name, type)VALUES ('Band 9', 'JobLevel');