<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/input_map_req_1.map" md5sum="5a4ff87fb17935bb247d1da15fdac770" version="7.0.500" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.500
*
*   Mapping file:		input_map_req_1.map
*   Map declaration(s):	input_map_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FOrderManagementLib%252FItemServiceIF%257DretrieveItemRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FDBMSServiceMediation%252FJDBCOutboundInterface%257DretrieveDbadminItemBGRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in2="http://OrderManagementLib"
    xmlns:in="http://OrderManagementLib/ItemServiceIF"
    xmlns:in3="wsdl.http://OrderManagementLib/ItemServiceIF"
    xmlns:out2="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminitemcontainer"
    xmlns:out="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminorderheadercontainer"
    xmlns:out3="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminitemwhs"
    xmlns:out4="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminitemwhsbg"
    xmlns:io="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out5="http://com/ibm/j2ca/fault"
    xmlns:io2="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out6="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminitemwhscontainer"
    xmlns:out7="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminorderheader"
    xmlns:out8="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminitem"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:out9="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminorderheaderbg"
    xmlns:out10="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadminitembg"
    xmlns:out11="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/metadata"
    xmlns:out12="http://com/ibm/j2ca/fault/afcfault"
    xmlns:out13="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadmincustomercontainer"
    xmlns:io3="http://www.w3.org/2003/05/soap-envelope"
    xmlns:out14="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadmincustomer"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out15="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/existsresult"
    xmlns:out16="http://www.ibm.com/xmlns/prod/websphere/j2ca/jdbc/dbadmincustomerbg"
    xmlns:out17="wsdl.http://DBMSServiceMediation/JDBCOutboundInterface"
    xmlns:out18="http://DBMSServiceMediation/JDBCOutboundInterface"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out19="http://www.ibm.com/xmlns/prod/websphere/bo/6.0.0"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://DBMSServiceMediation/xslt/input_map_req_1"
    exclude-result-prefixes="xalan str set in math map exsl in2 date in3"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:input_map_req_1"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map_req_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out17:retrieveDbadminItemBGRequestMsg'"/>
      </xsl:attribute>
      <out18:retrieveDbadminItemBG>
        <out18:retrieveDbadminItemBGInput>
          <!-- a simple mapping with no associated source:  to "out19:changeSummary"(ChangeSummaryType) -->
          <out19:changeSummary>
            <xsl:text>R</xsl:text>
          </out19:changeSummary>
          <DbadminItem>
            <!-- a simple data mapping: "in:retrieveItem/item/itemID"(string) to "itemid"(string) -->
            <xsl:if test="in:retrieveItem/item/itemID">
              <itemid>
                <xsl:value-of select="in:retrieveItem/item/itemID"/>
              </itemid>
            </xsl:if>
            <price xsi:nil="true"/>
            <warehouses xsi:nil="true"/>
          </DbadminItem>
        </out18:retrieveDbadminItemBGInput>
      </out18:retrieveDbadminItemBG>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map_req_12">
    <xsl:param name="body"/>
    <out18:retrieveDbadminItemBG>
      <out18:retrieveDbadminItemBGInput>
        <!-- a simple mapping with no associated source:  to "out19:changeSummary"(ChangeSummaryType) -->
        <out19:changeSummary>
          <xsl:text>R</xsl:text>
        </out19:changeSummary>
        <DbadminItem>
          <!-- a simple data mapping: "$body/in:retrieveItem/item/itemID"(string) to "itemid"(string) -->
          <xsl:if test="$body/in:retrieveItem/item/itemID">
            <itemid>
              <xsl:value-of select="$body/in:retrieveItem/item/itemID"/>
            </itemid>
          </xsl:if>
          <price xsi:nil="true"/>
          <warehouses xsi:nil="true"/>
        </DbadminItem>
      </out18:retrieveDbadminItemBGInput>
    </out18:retrieveDbadminItemBG>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
